---
title: "615 Pre_EDA"
group: "Akatsuki"
output: html_document
---
## Load Package & Read the Data
```{r}
library(tidyverse)

library(scales) 

library(readr)

library(dplyr)

library(stats)

library(factoextra) # clustering algorithms & visualization

library(corrplot)

library(graphics)

library(cluster)    # clustering algorithms

frm_NCBI <- read.csv('framingham.csv')
frm_ktrain <- read_csv('frmgham2.csv')

problems(frm_NCBI)
problems(frm_k)
```

```{r}
# Principal component analysis

frm_ktrain <- read.csv('framingham.csv')

res.pca <- prcomp(na.omit(frm_ktrain[,c(2:6, 8:14)], center = TRU, scale = TRUE))


fviz_eig(res.pca) #plot one

fviz_pca_biplot(res.pca) #plot two

fviz_pca_ind(res.pca) #gives a scatter plot. very messy

summary(res.pca) ##As you can see, principal components 1 and 2 have the highest standard deviation, use them

``` 

```{r}

#VARIATION PLOT for VARIANCE
#frm_ktrain <- read_csv('frmgham2.csv')
#frm_NCBI <- read.csv('framingham.csv') #used this
var <- get_pca_var(res.pca)
corrplot(var$cos2, is.corr=FALSE)

frm_ktrain.clean <-frm_ktrain %>% mutate_at(vars(SEX,CURSMOKE, DIABETES, BPMEDS, educ, PREVCHD, PREVAP, PREVMI, PREVSTRK, PREVHYP, PERIOD, DEATH, 
                                                  ANGINA, HOSPMI, MI_FCHD, ANYCHD, STROKE, CVD, HYPERTEN) , funs(factor(.)))
summary(frm_ktrain.clean)


```

```{r}

#my favorite one
#Panel correlation
#gives correlation between variables
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)

{

  usr <- par("usr"); on.exit(par(usr))

  par(usr = c(0, 1, 0, 1))

  r <- abs(cor(x, y))

  txt <- format(c(r, 0.123456789), digits = digits)[1]

  txt <- paste0(prefix, txt)

  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)

  text(0.5, 0.5, txt, cex = cex.cor * r)

}


#frm_ktrain <- read_csv('frmgham2.csv')

pairs( ~TOTCHOL+AGE+SYSBP+DIABP+BMI+HEARTRTE +GLUCOSE, data=frm_ktrain, na.action=na.omit,

       lower.panel = panel.smooth,

       upper.panel = panel.cor)

```

